#log
logging:
  config: classpath:logback-spring.xml

server-log-path: /app/log

spring:
  application.name: hospital
  profiles.active: prod
  main.allow-bean-definition-overriding: true

server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    threads:
      max: 128
      min-spare: 5
  servlet:
    context-path: /api2
#mybatis:
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  mapperLocations: classpath:mapper/**/*.xml

# 腾讯云密钥
secretId: AKIDbz80bvykGVS9YgX8SVGkxta0AtLWR5Ta
secretKey: rSlnX1E9nBI7fwxhAMHvHMBj00iETR7X
# cos名称
bucketName: img-1256886731