#log
logging:
  config: classpath:logback-spring.xml

server-log-path: /app/log

spring:
  application.name: hospital
  profiles.active: prod
  main.allow-bean-definition-overriding: true

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    threads:
      max: 128
      min-spare: 5
  servlet:
    context-path: /api
#mybatis:
mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml